[Nickname] # 现在没用
nickname = ""

[Discord_Server] # Discord Bot配置
token = "" # Discord Bot Token
discord_heartbeat = 30     # 心跳间隔（按秒计）
proxy = ""                # Discord代理设置，格式如：http://127.0.0.1:7890 或 socks5://127.0.0.1:7890，留空则不使用代理


[MaiBot_Server] # 连接麦麦的ws服务设置
platform_name = "discord" # 标识adapter的名称（必填）
host = "localhost"   # 麦麦在.env文件中设置的主机地址，即HOST字段
port = 8000          # 麦麦在.env文件中设置的端口，即PORT字段

[Chat] # 黑白名单功能
channel_list_type = "whitelist" # 群组名单类型，可选为：whitelist, blacklist
channel_list = [] # 群组名单
# 当channel_list_type为whitelist时，只有频道名单中的频道可以聊天
# 当channel_list_type为blacklist时，频道名单中的任何频道无法聊天
private_list_type = "whitelist" # 私聊名单类型，可选为：whitelist, blacklist
private_list = [] # 私聊名单
# 当private_list_type为whitelist时，只有私聊名单中的用户可以聊天
# 当private_list_type为blacklist时，私聊名单中的任何用户无法聊天
ban_user_id = [] # 全局禁止名单（全局禁止名单中的用户无法进行任何聊天）
enable_poke = true # 是否启用戳一戳功能

[Voice] # 发送语音设置
use_tts = false # 是否使用tts语音（请确保你配置了tts并有对应的adapter）

[Debug]
level = "INFO" # 日志等级（DEBUG, INFO, WARNING, ERROR）
